[application]
name = "iou-frontend"
default_platform = "web"
asset_dir = "assets"

[web.app]
title = "IOU-Modern - Informatie Ondersteunde Werkomgeving"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = [
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
]
script = [
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",
    "https://unpkg.com/vis-network@9.1.9/standalone/umd/vis-network.min.js",
]

[web.resource.dev]
script = []
